version: "1"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wintersite
      MYSQL_DATABASE: wintersite
      MYSQL_USER: wintersite
      MYSQL_PASSWORD: wintersite
    
  wintersite:
    depends_on:
      - db
    image: wintersite:latest
    volumes:
      - wintersite_data:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      wintersite_DB_HOST: db:3306
      wintersite_DB_USER: wintersite
      wintersite_DB_PASSWORD: wintersite
      wintersite_DB_NAME: wintersite
volumes:
  db_data: {}
  wintersite_data: {/Users/gustavo/localhost/wintersite/site}
