version: "1"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewintercms
      MYSQL_DATABASE: wintercms
      MYSQL_USER: wintercms
      MYSQL_PASSWORD: wintercms
    
  wintercms:
    depends_on:
      - db
    image: wintercms:latest
    volumes:
      - wintercms_data:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WINTERCMS_DB_HOST: db:3306
      WINTERCMS_DB_USER: wintercms
      WINTERCMS_DB_PASSWORD: wintercms
      WINTERCMS_DB_NAME: wintercms
volumes:
  db_data: {}
  wintercms_data: {}
